/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function hello_investment_portfolio(): string
export function calculate_sample_investment_portfolio(value: number): number
export function analyze_investment_portfolio_metrics(inputData: Array<number>): string
export function get_investment_portfolio_info(): string
export function validate_investment_portfolio_config(config: string): boolean
export function process_investment_portfolio_data(data: string): string