/**
 * HrController
 * Handles all hr domain operations
 */

import { Request, Response } from 'express';
import { BaseController } from '../base/base-controller';

export class HrController extends BaseController {
  /**
   * Get employee list
   */
  async getEmployees(req: Request, res: Response): Promise<void> {
    try {
      // Extract query parameters for filtering and pagination
      const { department, status, page = 1, limit = 50 } = req.query;
      const offset = (Number(page) - 1) * Number(limit);

      // Mock employee data - in production, this would query a database
      const employees = [
        {
          id: 'EMP-001',
          firstName: 'John',
          lastName: 'Doe',
          email: 'john.doe@example.com',
          department: 'Engineering',
          position: 'Software Engineer',
          status: 'ACTIVE',
          hireDate: '2020-01-15',
          salary: 95000,
        },
        {
          id: 'EMP-002',
          firstName: 'Jane',
          lastName: 'Smith',
          email: 'jane.smith@example.com',
          department: 'Finance',
          position: 'Financial Analyst',
          status: 'ACTIVE',
          hireDate: '2019-05-20',
          salary: 85000,
        },
        // Additional employees would be loaded from database
      ];

      // Apply filters
      let filteredEmployees = employees;
      if (department) {
        filteredEmployees = filteredEmployees.filter((e) => e.department === department);
      }
      if (status) {
        filteredEmployees = filteredEmployees.filter((e) => e.status === status);
      }

      // Apply pagination
      const paginatedEmployees = filteredEmployees.slice(offset, offset + Number(limit));

      const result = {
        employees: paginatedEmployees,
        pagination: {
          total: filteredEmployees.length,
          page: Number(page),
          limit: Number(limit),
          totalPages: Math.ceil(filteredEmployees.length / Number(limit)),
        },
        timestamp: new Date().toISOString(),
      };

      this.sendSuccess(res, result, 'Employee list retrieved successfully');
    } catch (error) {
      this.sendError(res, (error as Error).message || 'Failed to get employees', 500);
    }
  }

  /**
   * Create new employee
   */
  async createEmployee(req: Request, res: Response): Promise<void> {
    try {
      // Validate required fields
      const { firstName, lastName, email, department, position, hireDate, salary } = req.body;

      if (!firstName || !lastName || !email || !department || !position) {
        this.sendError(res, 'Missing required fields', 400);
        return;
      }

      // Validate email format
      const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
      if (!emailRegex.test(email)) {
        this.sendError(res, 'Invalid email format', 400);
        return;
      }

      // Generate employee ID (in production, would be auto-generated by database)
      const employeeId = `EMP-${Date.now().toString().slice(-6)}`;

      // Create employee record
      const newEmployee = {
        id: employeeId,
        firstName,
        lastName,
        email,
        department,
        position,
        status: 'ACTIVE',
        hireDate: hireDate || new Date().toISOString().split('T')[0],
        salary: salary || 0,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      };

      // In production, would save to database
      // await db.employees.insert(newEmployee);

      this.sendSuccess(res, { employee: newEmployee }, 'Employee created successfully', 201);
    } catch (error) {
      this.sendError(res, (error as Error).message || 'Failed to create employee', 500);
    }
  }

  /**
   * Get employee by ID
   */
  async getEmployeeById(req: Request, res: Response): Promise<void> {
    try {
      const { id } = req.params;

      if (!id) {
        this.sendError(res, 'Employee ID is required', 400);
        return;
      }

      // Mock employee lookup - in production, would query database
      // const employee = await db.employees.findById(id);
      const mockEmployee = {
        id,
        firstName: 'John',
        lastName: 'Doe',
        email: 'john.doe@example.com',
        department: 'Engineering',
        position: 'Software Engineer',
        status: 'ACTIVE',
        hireDate: '2020-01-15',
        salary: 95000,
        benefits: ['Health Insurance', '401k', 'PTO'],
        manager: 'MGR-001',
        location: 'New York, NY',
        createdAt: '2020-01-15T00:00:00.000Z',
        updatedAt: new Date().toISOString(),
      };

      this.sendSuccess(res, { employee: mockEmployee }, 'Employee retrieved successfully');
    } catch (error) {
      this.sendError(res, (error as Error).message || 'Failed to get employee by ID', 500);
    }
  }

  /**
   * Update employee information
   */
  async updateEmployee(req: Request, res: Response): Promise<void> {
    try {
      const { id } = req.params;
      const updates = req.body;

      if (!id) {
        this.sendError(res, 'Employee ID is required', 400);
        return;
      }

      // Validate email if being updated
      if (updates.email) {
        const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
        if (!emailRegex.test(updates.email)) {
          this.sendError(res, 'Invalid email format', 400);
          return;
        }
      }

      // In production, would update in database
      // const updatedEmployee = await db.employees.update(id, updates);
      const updatedEmployee = {
        id,
        ...updates,
        updatedAt: new Date().toISOString(),
      };

      this.sendSuccess(res, { employee: updatedEmployee }, 'Employee updated successfully');
    } catch (error) {
      this.sendError(res, (error as Error).message || 'Failed to update employee', 500);
    }
  }

  /**
   * Get payroll data
   */
  async getPayroll(req: Request, res: Response): Promise<void> {
    try {
      const { employeeId, period, status } = req.query;

      // Mock payroll data - in production, would query database
      const payrollRecords = [
        {
          id: 'PAY-001',
          employeeId: 'EMP-001',
          employeeName: 'John Doe',
          period: '2024-01',
          grossPay: 7916.67,
          deductions: {
            federalTax: 1500.0,
            stateTax: 400.0,
            medicare: 114.79,
            socialSecurity: 490.83,
            healthInsurance: 250.0,
          },
          netPay: 5161.05,
          status: 'PROCESSED',
          payDate: '2024-01-31',
          processedAt: '2024-01-28T10:00:00.000Z',
        },
      ];

      // Apply filters
      let filteredPayroll = payrollRecords;
      if (employeeId) {
        filteredPayroll = filteredPayroll.filter((p) => p.employeeId === employeeId);
      }
      if (period) {
        filteredPayroll = filteredPayroll.filter((p) => p.period === period);
      }
      if (status) {
        filteredPayroll = filteredPayroll.filter((p) => p.status === status);
      }

      const result = {
        payroll: filteredPayroll,
        summary: {
          totalGrossPay: filteredPayroll.reduce((sum, p) => sum + p.grossPay, 0),
          totalNetPay: filteredPayroll.reduce((sum, p) => sum + p.netPay, 0),
          count: filteredPayroll.length,
        },
        timestamp: new Date().toISOString(),
      };

      this.sendSuccess(res, result, 'Payroll data retrieved successfully');
    } catch (error) {
      this.sendError(res, (error as Error).message || 'Failed to get payroll', 500);
    }
  }

  /**
   * Process payroll run
   */
  async processPayroll(req: Request, res: Response): Promise<void> {
    try {
      const { period, employeeIds } = req.body;

      if (!period) {
        this.sendError(res, 'Payroll period is required', 400);
        return;
      }

      // Validate period format (YYYY-MM)
      const periodRegex = /^\d{4}-\d{2}$/;
      if (!periodRegex.test(period)) {
        this.sendError(res, 'Invalid period format. Use YYYY-MM', 400);
        return;
      }

      // In production, would process payroll for all or specified employees
      const processedCount = employeeIds ? employeeIds.length : 100; // Mock count

      const result = {
        payrollRun: {
          id: `PR-${Date.now()}`,
          period,
          status: 'PROCESSING',
          employeesProcessed: processedCount,
          totalGrossPay: processedCount * 7916.67, // Mock calculation
          totalDeductions: processedCount * 2755.62,
          totalNetPay: processedCount * 5161.05,
          initiatedBy: 'SYSTEM', // Would use actual user from auth
          initiatedAt: new Date().toISOString(),
        },
        message: `Payroll processing initiated for ${processedCount} employees`,
        timestamp: new Date().toISOString(),
      };

      this.sendSuccess(res, result, 'Payroll processing initiated successfully', 202);
    } catch (error) {
      this.sendError(res, (error as Error).message || 'Failed to process payroll', 500);
    }
  }

  /**
   * Get performance reviews
   */
  async getPerformanceReviews(req: Request, res: Response): Promise<void> {
    try {
      const { employeeId, reviewPeriod, status } = req.query;

      // Mock performance review data
      const reviews = [
        {
          id: 'REV-001',
          employeeId: 'EMP-001',
          employeeName: 'John Doe',
          reviewPeriod: '2024-Q1',
          reviewDate: '2024-04-01',
          reviewer: 'MGR-001',
          reviewerName: 'Sarah Johnson',
          ratings: {
            technicalSkills: 4.5,
            communication: 4.0,
            teamwork: 4.5,
            leadership: 4.0,
            problemSolving: 4.5,
          },
          overallRating: 4.3,
          strengths: ['Strong technical skills', 'Excellent team player'],
          areasForImprovement: ['Time management', 'Delegation'],
          goals: ['Lead major project', 'Mentor junior developers'],
          status: 'COMPLETED',
          comments: 'Excellent performance throughout the quarter',
          createdAt: '2024-04-01T00:00:00.000Z',
          updatedAt: '2024-04-01T10:00:00.000Z',
        },
      ];

      // Apply filters
      let filteredReviews = reviews;
      if (employeeId) {
        filteredReviews = filteredReviews.filter((r) => r.employeeId === employeeId);
      }
      if (reviewPeriod) {
        filteredReviews = filteredReviews.filter((r) => r.reviewPeriod === reviewPeriod);
      }
      if (status) {
        filteredReviews = filteredReviews.filter((r) => r.status === status);
      }

      const result = {
        reviews: filteredReviews,
        summary: {
          total: filteredReviews.length,
          averageRating:
            filteredReviews.reduce((sum, r) => sum + r.overallRating, 0) /
            (filteredReviews.length || 1),
        },
        timestamp: new Date().toISOString(),
      };

      this.sendSuccess(res, result, 'Performance reviews retrieved successfully');
    } catch (error) {
      this.sendError(res, (error as Error).message || 'Failed to get performance reviews', 500);
    }
  }

  /**
   * Create performance review
   */
  async createPerformanceReview(req: Request, res: Response): Promise<void> {
    try {
      const { employeeId, reviewPeriod, ratings, strengths, areasForImprovement, goals, comments } =
        req.body;

      // Validate required fields
      if (!employeeId || !reviewPeriod || !ratings) {
        this.sendError(res, 'Missing required fields: employeeId, reviewPeriod, ratings', 400);
        return;
      }

      // Validate ratings structure
      const requiredRatingFields = [
        'technicalSkills',
        'communication',
        'teamwork',
        'leadership',
        'problemSolving',
      ];
      for (const field of requiredRatingFields) {
        if (typeof ratings[field] !== 'number' || ratings[field] < 0 || ratings[field] > 5) {
          this.sendError(res, `Invalid rating for ${field}. Must be between 0 and 5`, 400);
          return;
        }
      }

      // Calculate overall rating
      const ratingValues = Object.values(ratings) as number[];
      const overallRating =
        ratingValues.reduce((sum, val) => sum + val, 0) / ratingValues.length;

      // Create review record
      const newReview = {
        id: `REV-${Date.now().toString().slice(-6)}`,
        employeeId,
        reviewPeriod,
        reviewDate: new Date().toISOString().split('T')[0],
        reviewer: 'CURRENT_USER', // Would be from auth context
        ratings,
        overallRating: Math.round(overallRating * 10) / 10,
        strengths: strengths || [],
        areasForImprovement: areasForImprovement || [],
        goals: goals || [],
        status: 'DRAFT',
        comments: comments || '',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      };

      this.sendSuccess(res, { review: newReview }, 'Performance review created successfully', 201);
    } catch (error) {
      this.sendError(
        res,
        (error as Error).message || 'Failed to create performance review',
        500
      );
    }
  }

  /**
   * Get time tracking data
   */
  async getTimeTracking(req: Request, res: Response): Promise<void> {
    try {
      const { employeeId, startDate, endDate, projectId } = req.query;

      // Mock time tracking data
      const timeEntries = [
        {
          id: 'TIME-001',
          employeeId: 'EMP-001',
          employeeName: 'John Doe',
          date: '2024-01-15',
          projectId: 'PROJ-001',
          projectName: 'Enterprise Portal',
          taskDescription: 'Backend API development',
          hours: 8.0,
          billable: true,
          status: 'APPROVED',
          approvedBy: 'MGR-001',
          createdAt: '2024-01-15T17:00:00.000Z',
        },
        {
          id: 'TIME-002',
          employeeId: 'EMP-001',
          employeeName: 'John Doe',
          date: '2024-01-16',
          projectId: 'PROJ-001',
          projectName: 'Enterprise Portal',
          taskDescription: 'Code review and testing',
          hours: 7.5,
          billable: true,
          status: 'SUBMITTED',
          createdAt: '2024-01-16T17:00:00.000Z',
        },
      ];

      // Apply filters
      let filteredEntries = timeEntries;
      if (employeeId) {
        filteredEntries = filteredEntries.filter((e) => e.employeeId === employeeId);
      }
      if (startDate) {
        filteredEntries = filteredEntries.filter((e) => e.date >= startDate);
      }
      if (endDate) {
        filteredEntries = filteredEntries.filter((e) => e.date <= endDate);
      }
      if (projectId) {
        filteredEntries = filteredEntries.filter((e) => e.projectId === projectId);
      }

      const result = {
        timeEntries: filteredEntries,
        summary: {
          totalHours: filteredEntries.reduce((sum, e) => sum + e.hours, 0),
          billableHours: filteredEntries
            .filter((e) => e.billable)
            .reduce((sum, e) => sum + e.hours, 0),
          entriesCount: filteredEntries.length,
        },
        timestamp: new Date().toISOString(),
      };

      this.sendSuccess(res, result, 'Time tracking data retrieved successfully');
    } catch (error) {
      this.sendError(res, (error as Error).message || 'Failed to get time tracking', 500);
    }
  }

  /**
   * Record time entry
   */
  async recordTimeEntry(req: Request, res: Response): Promise<void> {
    try {
      const { employeeId, date, projectId, taskDescription, hours, billable } = req.body;

      // Validate required fields
      if (!employeeId || !date || !projectId || !hours) {
        this.sendError(res, 'Missing required fields: employeeId, date, projectId, hours', 400);
        return;
      }

      // Validate date format (YYYY-MM-DD)
      const dateRegex = /^\d{4}-\d{2}-\d{2}$/;
      if (!dateRegex.test(date)) {
        this.sendError(res, 'Invalid date format. Use YYYY-MM-DD', 400);
        return;
      }

      // Validate hours (must be positive and reasonable)
      if (typeof hours !== 'number' || hours <= 0 || hours > 24) {
        this.sendError(res, 'Invalid hours. Must be between 0 and 24', 400);
        return;
      }

      // Create time entry record
      const newTimeEntry = {
        id: `TIME-${Date.now().toString().slice(-6)}`,
        employeeId,
        date,
        projectId,
        taskDescription: taskDescription || '',
        hours,
        billable: billable !== undefined ? billable : true,
        status: 'SUBMITTED',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      };

      // In production, would save to database
      // await db.timeEntries.insert(newTimeEntry);

      this.sendSuccess(res, { timeEntry: newTimeEntry }, 'Time entry recorded successfully', 201);
    } catch (error) {
      this.sendError(res, (error as Error).message || 'Failed to record time entry', 500);
    }
  }
}

// Export singleton instance
export const hrController = new HrController();
