/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function hello_smart_grid(): string
export function calculate_sample_smart_grid(value: number): number
export function analyze_smart_grid_metrics(inputData: Array<number>): string
export function get_smart_grid_info(): string
export function validate_smart_grid_config(config: string): boolean
export function process_smart_grid_data(data: string): string