/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function hello_smart_city(): string
export function calculate_sample_smart_city(value: number): number
export function analyze_smart_city_metrics(inputData: Array<number>): string
export function get_smart_city_info(): string
export function validate_smart_city_config(config: string): boolean
export function process_smart_city_data(data: string): string