/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function hello_multi_currency(): string
export function calculate_sample_multi_currency(value: number): number
export function analyze_multi_currency_metrics(inputData: Array<number>): string
export function get_multi_currency_info(): string
export function validate_multi_currency_config(config: string): boolean
export function process_multi_currency_data(data: string): string