/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function sum(a: number, b: number): number
export interface RiskAssessment {
  id: string
  assessmentName: string
  riskCategory: string
  riskDescription: string
  likelihood: string
  impact: string
  riskScore: number
  riskLevel: string
  owner: string
  status: string
}
export interface RiskMitigation {
  strategy: string
  actions: Array<MitigationAction>
  residualRiskScore: number
  cost?: number
}
export interface MitigationAction {
  actionId: string
  description: string
  assignedTo: string
  status: string
  priority: string
}
export interface RiskMetrics {
  totalRisks: number
  riskDistribution: Array<RiskDistribution>
  highRisks: Array<RiskAssessment>
  overdueMitigations: number
  averageRiskScore: number
}
export interface RiskDistribution {
  level: string
  count: number
  percentage: number
}
export declare function calculateRiskScore(likelihood: string, impact: string): number
export declare function determineRiskLevel(score: number): string
export declare function createRiskAssessment(assessmentName: string, riskCategory: string, riskDescription: string, likelihood: string, impact: string, owner: string, status: string): RiskAssessment
export declare function calculateResidualRisk(baseScore: number, mitigationEffectiveness: number): number
export declare function generateRiskMetrics(risks: Array<RiskAssessment>): RiskMetrics
export declare function assessPortfolioRisk(risks: Array<RiskAssessment>): number
export interface ComplianceFramework {
  id: string
  frameworkCode: string
  name: string
  description: string
  regulatoryBody: string
  applicableRegions: Array<string>
  requirementsCount: number
  complianceRate: number
}
export interface ComplianceRequirement {
  requirementId: string
  title: string
  description: string
  category: string
  mandatory: boolean
  assessmentFrequency: string
  complianceStatus: string
  lastAssessmentScore: number
}
export interface ComplianceAssessment {
  frameworkId: string
  overallComplianceRate: number
  riskLevel: string
  nonCompliantCount: number
  recommendations: Array<string>
  nextAssessmentDate: string
}
export interface AuditFinding {
  findingId: string
  category: string
  description: string
  riskLevel: string
  status: string
  correctiveActionsCount: number
}
export interface ComplianceMetrics {
  totalFrameworks: number
  averageComplianceRate: number
  criticalFindings: number
  overdueActions: number
  trainingComplianceRate: number
}
export declare function calculateComplianceScore(totalRequirements: number, compliantRequirements: number, weightedScores: Array<number>): number
export declare function determineComplianceRiskLevel(complianceRate: number, criticalFindings: number): string
export declare function assessFrameworkCompliance(frameworkId: string, requirements: Array<ComplianceRequirement>): ComplianceAssessment
export declare function calculateTrainingComplianceRate(totalEmployees: number, employeesWithCurrentTraining: number, overdueRenewals: number): number
export declare function validateRequirementCompliance(requirement: ComplianceRequirement, evidenceCount: number, lastAssessmentDaysAgo: number): number
export declare function generateComplianceMetrics(frameworks: Array<ComplianceFramework>, findings: Array<AuditFinding>, trainingComplianceRate: number): ComplianceMetrics
export declare function calculateAuditScore(totalRequirementsChecked: number, requirementsPassed: number, minorFindings: number, majorFindings: number, criticalFindings: number): number
export interface Document {
  id: string
  documentNumber: string
  title: string
  description: string
  documentType: string
  category: string
  tags: Array<string>
  version: string
  status: string
  securityClassification: string
  owner: string
  fileSize?: number
  contentHash?: string
}
export interface DocumentSearchResult {
  documents: Array<Document>
  totalCount: number
  searchTimeMs: number
  relevanceScores: Array<number>
}
export interface DocumentMetrics {
  totalDocuments: number
  documentsByStatus: Array<StatusCount>
  documentsByType: Array<TypeCount>
  averageFileSize: number
  documentsNearExpiry: number
  overdueReviews: number
}
export interface StatusCount {
  status: string
  count: number
  percentage: number
}
export interface TypeCount {
  documentType: string
  count: number
  totalSize: number
}
export interface SearchCriteria {
  title?: string
  documentType?: string
  category?: string
  tags: Array<string>
  status?: string
  owner?: string
  dateFrom?: string
  dateTo?: string
}
export declare function calculateDocumentRelevanceScore(document: Document, searchQuery: string, criteria: SearchCriteria): number
export declare function searchDocuments(documents: Array<Document>, searchQuery: string, criteria: SearchCriteria, limit: number): DocumentSearchResult
export declare function calculateContentHash(content: string): string
export declare function validateDocumentTitle(title: string): boolean
export declare function generateDocumentNumber(documentType: string, sequence: number): string
export declare function calculateRetentionExpiryDate(creationDate: string, retentionPeriodMonths: number): string
export declare function analyzeDocumentMetrics(documents: Array<Document>): DocumentMetrics
export declare function classifyDocumentByContent(content: string, title: string): string
export interface WorkflowDefinition {
  id: string
  workflowCode: string
  name: string
  description: string
  category: string
  version: string
  status: string
  stepsCount: number
  estimatedDurationHours: number
}
export interface WorkflowStep {
  stepId: string
  stepName: string
  stepType: string
  assigneeType: string
  assigneeId?: string
  timeoutHours?: number
  order: number
  isParallel: boolean
  required: boolean
}
export interface WorkflowInstance {
  id: string
  workflowId: string
  instanceNumber: string
  status: string
  currentStepId: string
  initiatedBy: string
  startTimestamp: number
  completionTimestamp?: number
  progressPercentage: number
}
export interface WorkflowMetrics {
  totalInstances: number
  completedInstances: number
  failedInstances: number
  averageCompletionTimeHours: number
  successRate: number
  activeInstances: number
  bottleneckSteps: Array<string>
}
export interface StepExecution {
  stepId: string
  instanceId: string
  status: string
  startedAt: number
  completedAt?: number
  durationMinutes?: number
  performer: string
  outcome: string
}
export declare function calculateWorkflowProgress(steps: Array<WorkflowStep>, completedSteps: Array<string>): number
export declare function estimateWorkflowDuration(steps: Array<WorkflowStep>): number
export declare function identifyWorkflowBottlenecks(executions: Array<StepExecution>): Array<string>
export declare function calculateWorkflowSuccessRate(instances: Array<WorkflowInstance>): number
export declare function generateWorkflowMetrics(instances: Array<WorkflowInstance>, executions: Array<StepExecution>): WorkflowMetrics
export declare function optimizeWorkflowPath(steps: Array<WorkflowStep>, constraints: Array<string>): Array<string>
export declare function validateWorkflowDefinition(definition: WorkflowDefinition, steps: Array<WorkflowStep>): Array<string>
export declare function calculateStepPerformanceScore(executions: Array<StepExecution>): number
export interface QualityMetrics {
  defectRate: number
  firstPassYield: number
  customerSatisfaction: number
  processCapability: number
  supplierQualityRating: number
  overallQualityScore: number
}
export interface DefectData {
  defectId: string
  defectType: string
  severity: string
  detectionStage: string
  rootCause: string
  costImpact: number
  occurrenceCount: number
}
export interface ProcessCapability {
  processName: string
  cp: number
  cpk: number
  pp: number
  ppk: number
  sigmaLevel: number
}
export interface QualityInspection {
  inspectionId: string
  productBatch: string
  inspector: string
  totalUnits: number
  passedUnits: number
  failedUnits: number
  defectsFound: Array<DefectData>
  inspectionScore: number
}
export interface SixSigmaAnalysis {
  processName: string
  dpmo: number
  sigmaLevel: number
  processYield: number
  improvementPotential: number
  recommendedActions: Array<string>
}
export declare function calculateDefectRate(totalUnits: number, defectiveUnits: number): number
export declare function calculateFirstPassYield(totalUnits: number, firstPassUnits: number): number
export declare function calculateProcessCapability(upperSpecLimit: number, lowerSpecLimit: number, processMean: number, processStdDev: number): ProcessCapability
export declare function calculateDpmo(defects: number, units: number, opportunitiesPerUnit: number): number
export declare function calculateSigmaLevel(dpmo: number): number
export declare function performSixSigmaAnalysis(processName: string, defects: number, units: number, opportunitiesPerUnit: number): SixSigmaAnalysis
export declare function calculateCustomerSatisfactionScore(ratings: Array<number>, complaints: number, totalCustomers: number): number
export declare function analyzeDefectPatterns(defects: Array<DefectData>): Array<string>
export declare function calculateSupplierQualityRating(deliveredBatches: number, defectiveBatches: number, averageDefectRate: number, onTimeDeliveryRate: number): number
export declare function generateQualityMetrics(inspections: Array<QualityInspection>, defects: Array<DefectData>, customerRatings: Array<number>, customerComplaints: number, totalCustomers: number): QualityMetrics
export declare function calculateQualityCost(preventionCosts: number, appraisalCosts: number, internalFailureCosts: number, externalFailureCosts: number, totalRevenue: number): number
export interface InventoryItem {
  itemId: string
  itemCode: string
  description: string
  category: string
  unitCost: number
  currentStock: number
  reservedStock: number
  availableStock: number
  reorderPoint: number
  maxStockLevel: number
  abcClassification: string
}
export interface EoqCalculation {
  itemId: string
  economicOrderQuantity: number
  totalAnnualCost: number
  orderingCostComponent: number
  holdingCostComponent: number
  orderFrequency: number
  optimalCycleTimeDays: number
}
export interface SafetyStockCalculation {
  itemId: string
  safetyStock: number
  serviceLevel: number
  demandVariability: number
  leadTimeVariability: number
  reorderPoint: number
}
export interface AbcAnalysis {
  itemId: string
  annualUsageValue: number
  percentageOfTotalValue: number
  cumulativePercentage: number
  abcClass: string
  managementPriority: string
}
export interface InventoryMetrics {
  totalItems: number
  totalValue: number
  inventoryTurnover: number
  daysSalesOutstanding: number
  stockoutRiskItems: number
  excessStockItems: number
  abcDistribution: Array<ABCClassDistribution>
}
export interface AbcClassDistribution {
  class: string
  itemCount: number
  valuePercentage: number
}
export interface InventoryOptimization {
  itemId: string
  currentCost: number
  optimizedCost: number
  potentialSavings: number
  recommendedOrderQuantity: number
  recommendedSafetyStock: number
  optimizationActions: Array<string>
}
export declare function calculateEoq(annualDemand: number, orderingCost: number, holdingCostRate: number, unitCost: number): EoqCalculation
export declare function calculateSafetyStock(leadTimeDays: number, dailyDemandMean: number, dailyDemandStdDev: number, leadTimeStdDev: number, serviceLevel: number): SafetyStockCalculation
export declare function performAbcAnalysis(items: Array<InventoryItem>, annualDemands: Array<number>): Array<AbcAnalysis>
export declare function calculateInventoryTurnover(costOfGoodsSold: number, averageInventoryValue: number): number
export declare function calculateDaysSalesOutstanding(averageInventoryValue: number, dailyCostOfGoodsSold: number): number
export declare function identifyStockoutRiskItems(items: Array<InventoryItem>, leadTimeDays: number): Array<string>
export declare function identifyExcessStockItems(items: Array<InventoryItem>, monthsThreshold: number): Array<string>
export declare function generateInventoryMetrics(items: Array<InventoryItem>, annualDemands: Array<number>, costOfGoodsSold: number): InventoryMetrics
export declare function optimizeInventoryItem(item: InventoryItem, annualDemand: number, orderingCost: number, holdingCostRate: number, leadTimeDays: number, serviceLevel: number): InventoryOptimization
export interface IntegrationEndpoint {
  id: string
  name: string
  endpointType: string
  url: string
  method: string
  status: string
  lastSuccess?: number
  errorCount: number
  averageResponseTime: number
}
export interface DataTransformation {
  transformationId: string
  sourceFormat: string
  targetFormat: string
  fieldMappings: Array<FieldMapping>
  validationRules: Array<ValidationRule>
  transformationSuccessRate: number
}
export interface FieldMapping {
  sourceField: string
  targetField: string
  transformationRule: string
  isRequired: boolean
  dataType: string
}
export interface ValidationRule {
  ruleId: string
  fieldName: string
  ruleType: string
  ruleExpression: string
  errorMessage: string
}
export interface IntegrationMetrics {
  totalEndpoints: number
  activeEndpoints: number
  failedEndpoints: number
  averageResponseTime: number
  totalRequestsToday: number
  errorRate: number
  dataThroughputMb: number
}
export interface SyncResult {
  syncId: string
  sourceSystem: string
  targetSystem: string
  recordsProcessed: number
  recordsSuccessful: number
  recordsFailed: number
  syncDurationMs: number
  errors: Array<string>
}
export interface ApiHealthCheck {
  endpointId: string
  isHealthy: boolean
  responseTimeMs: number
  statusCode: number
  errorMessage?: string
  checkTimestamp: number
}
export declare function validateJsonData(jsonString: string, schemaRules: Array<ValidationRule>): Array<string>
export declare function transformData(sourceData: string, transformation: DataTransformation): string
export declare function calculateDataQualityScore(totalRecords: number, validRecords: number, duplicateRecords: number, incompleteRecords: number): number
export declare function performDataSync(sourceData: Array<string>, targetFormat: string, transformation: DataTransformation): SyncResult
export declare function checkApiHealth(endpoint: IntegrationEndpoint): ApiHealthCheck
export declare function calculateIntegrationMetrics(endpoints: Array<IntegrationEndpoint>, dailyRequests: number, dailyErrors: number, dataVolumeMb: number): IntegrationMetrics
export declare function detectDataAnomalies(dataPoints: Array<number>, thresholdMultiplier: number): Array<number>
export declare function calculateEtlPerformance(extractionTimeMs: number, transformationTimeMs: number, loadingTimeMs: number, recordsProcessed: number): number
export declare function generateIntegrationReport(syncResults: Array<SyncResult>, healthChecks: Array<ApiHealthCheck>): string
export interface MaintenanceTask {
  taskId: string
  assetId: string
  taskType: string
  priority: string
  estimatedHours: number
  estimatedCost: number
  dueDate: number
  status: string
}
export interface MaintenanceSchedule {
  scheduleId: string
  assetId: string
  maintenanceType: string
  frequencyDays: number
  nextDueDate: number
  estimatedDurationHours: number
  priorityScore: number
}
export interface MaintenanceMetrics {
  totalTasks: number
  completedTasks: number
  overdueTasks: number
  averageCompletionTime: number
  maintenanceCostTotal: number
  equipmentUptimePercentage: number
  preventiveVsReactiveRatio: number
}
export declare function calculateMaintenancePriorityScore(assetCriticality: number, daysOverdue: number, estimatedCost: number, safetyImpact: number): number
export declare function optimizeMaintenanceSchedule(tasks: Array<MaintenanceTask>, availableHoursPerDay: number, maxDaysAhead: number): Array<string>
export declare function calculateEquipmentUptime(totalOperatingHours: number, downtimeHours: number): number
export declare function generateMaintenanceMetrics(tasks: Array<MaintenanceTask>, totalEquipmentHours: number, downtimeHours: number): MaintenanceMetrics
export interface Asset {
  assetId: string
  assetCode: string
  assetName: string
  assetType: string
  acquisitionCost: number
  acquisitionDate: number
  usefulLifeYears: number
  currentBookValue: number
  accumulatedDepreciation: number
  status: string
}
export interface DepreciationCalculation {
  assetId: string
  method: string
  annualDepreciation: number
  monthlyDepreciation: number
  remainingBookValue: number
  yearsRemaining: number
  fullyDepreciatedDate: number
}
export interface AssetMetrics {
  totalAssets: number
  totalAcquisitionCost: number
  totalCurrentValue: number
  totalDepreciation: number
  averageAssetAgeYears: number
  assetsDueForReplacement: number
  returnOnAssets: number
}
export declare function calculateStraightLineDepreciation(acquisitionCost: number, salvageValue: number, usefulLifeYears: number, yearsInService: number): DepreciationCalculation
export declare function calculateDecliningBalanceDepreciation(acquisitionCost: number, depreciationRate: number, yearsInService: number): DepreciationCalculation
export declare function calculateAssetAgeYears(acquisitionDate: number): number
export declare function calculateAssetUtilizationRate(actualUsageHours: number, availableHours: number): number
export declare function assessAssetReplacementNeed(asset: Asset, maintenanceCostAnnual: number, downtimeCostAnnual: number, replacementThresholdPercentage: number): boolean
export declare function calculateReturnOnAssets(netIncome: number, totalAssetValue: number): number
export declare function generateAssetMetrics(assets: Array<Asset>, annualNetIncome: number): AssetMetrics
export declare function optimizeAssetPortfolio(assets: Array<Asset>, budgetConstraint: number, replacementPriorityThreshold: number): Array<string>
/** Mathematical utilities for business calculations */
export declare function calculateCompoundInterest(principal: number, annualRate: number, compoundingFrequency: number, years: number): number
export declare function calculatePresentValue(futureValue: number, discountRate: number, periods: number): number
export declare function calculateNetPresentValue(cashFlows: Array<number>, discountRate: number): number
export declare function calculateInternalRateOfReturn(cashFlows: Array<number>, initialGuess: number): number
export declare function calculatePaybackPeriod(initialInvestment: number, annualCashFlows: Array<number>): number
export declare function calculateBreakEvenPoint(fixedCosts: number, variableCostPerUnit: number, sellingPricePerUnit: number): number
export declare function calculateRoi(gainFromInvestment: number, costOfInvestment: number): number
export declare function calculateWeightedAverage(values: Array<number>, weights: Array<number>): number
export declare function calculateStandardDeviation(values: Array<number>): number
export declare function calculateCorrelationCoefficient(xValues: Array<number>, yValues: Array<number>): number
export declare function calculateMovingAverage(values: Array<number>, windowSize: number): Array<number>
export declare function calculateGrowthRate(initialValue: number, finalValue: number, periods: number): number
export declare function calculateZScore(value: number, mean: number, standardDeviation: number): number
export declare function calculatePercentile(values: Array<number>, percentile: number): number
export interface PurchaseOrder {
  id: string
  supplierId: string
  orderDate: string
  totalAmount: number
  currency: string
  status: string
  items: Array<PurchaseOrderItem>
  deliveryDate: string
  terms: string
}
export interface PurchaseOrderItem {
  itemId: string
  description: string
  quantity: number
  unitPrice: number
  totalPrice: number
  deliveryDate: string
}
export interface SupplierScore {
  supplierId: string
  qualityScore: number
  deliveryScore: number
  priceCompetitiveness: number
  overallScore: number
  riskLevel: string
}
export interface RfqResponse {
  rfqId: string
  supplierId: string
  responseDate: string
  totalQuotedPrice: number
  deliveryTimeDays: number
  complianceScore: number
  competitivenessScore: number
}
export interface ProcurementAnalytics {
  totalSpend: number
  supplierCount: number
  averageOrderValue: number
  topSuppliers: Array<string>
  costSavings: number
  deliveryPerformance: number
}
export declare function calculatePurchaseOrderTotal(items: Array<PurchaseOrderItem>): number
export declare function calculateSupplierScore(qualityRating: number, onTimeDeliveryRate: number, priceCompetitiveness: number, paymentTermsCompliance: number): SupplierScore
export declare function calculateRfqCompetitiveness(quotedPrice: number, marketAveragePrice: number, deliveryDays: number, standardDeliveryDays: number): number
export declare function calculateProcurementSavings(baselineSpend: number, actualSpend: number): number
export declare function optimizePurchaseOrderTiming(demandForecast: Array<number>, leadTimeDays: number, safetyStockDays: number): Array<number>
export declare function calculateSupplierRiskAssessment(financialStabilityScore: number, geographicRiskScore: number, capacityUtilization: number, dependencyLevel: number): number
export declare function calculatePurchaseOrderDiscount(baseTotal: number, quantity: number, volumeDiscountThreshold: number, discountPercentage: number): number
export declare function generateProcurementAnalytics(orders: Array<PurchaseOrder>, targetSavingsPercentage: number): ProcurementAnalytics
export interface SalesOrder {
  id: string
  customerId: string
  orderDate: string
  totalAmount: number
  currency: string
  status: string
  items: Array<OrderItem>
  deliveryDate: string
  shippingMethod: string
}
export interface OrderItem {
  itemId: string
  productCode: string
  description: string
  quantity: number
  unitPrice: number
  discountPercentage: number
  totalPrice: number
  taxAmount: number
}
export interface PricingRule {
  ruleId: string
  customerTier: string
  productCategory: string
  quantityThreshold: number
  discountPercentage: number
  effectiveDate: string
  expiryDate: string
}
export interface OrderFulfillment {
  orderId: string
  fulfillmentStatus: string
  pickedItems: number
  packedItems: number
  shippedItems: number
  deliveredItems: number
  fulfillmentScore: number
}
export interface ShippingCalculation {
  shippingCost: number
  estimatedDeliveryDays: number
  shippingMethod: string
  insuranceCost: number
  totalShippingCost: number
}
export interface OrderAnalytics {
  totalOrders: number
  totalRevenue: number
  averageOrderValue: number
  fulfillmentRate: number
  onTimeDeliveryRate: number
  customerSatisfactionScore: number
}
export declare function calculateOrderTotal(items: Array<OrderItem>): number
export declare function calculateItemTotalPrice(quantity: number, unitPrice: number, discountPercentage: number): number
export declare function calculateDynamicPricing(basePrice: number, demandFactor: number, inventoryLevel: number, competitorPrice: number, customerTierMultiplier: number): number
export declare function calculateShippingCost(weightKg: number, distanceKm: number, shippingMethod: string, insuranceValue: number): ShippingCalculation
export declare function calculateOrderFulfillmentScore(totalItems: number, pickedItems: number, packedItems: number, shippedItems: number, deliveredItems: number): number
export declare function optimizeOrderBatching(orders: Array<string>, batchSizeLimit: number, priorityScores: Array<number>): Array<Array<string>>
export declare function calculateOrderPriorityScore(customerTier: string, orderValue: number, shippingMethod: string, ageHours: number): number
export declare function generateOrderAnalytics(orders: Array<SalesOrder>, targetFulfillmentRate: number): OrderAnalytics
export interface Account {
  accountId: string
  accountNumber: string
  accountName: string
  accountType: string
  balance: number
  currency: string
  isActive: boolean
}
export interface Transaction {
  transactionId: string
  accountId: string
  amount: number
  transactionType: string
  description: string
  transactionDate: string
  referenceNumber: string
}
export interface BudgetAnalysis {
  budgetCategory: string
  budgetedAmount: number
  actualAmount: number
  variance: number
  variancePercentage: number
  status: string
}
export interface CashFlowProjection {
  period: string
  openingBalance: number
  totalInflows: number
  totalOutflows: number
  netCashFlow: number
  closingBalance: number
}
export interface FinancialRatios {
  currentRatio: number
  quickRatio: number
  debtToEquity: number
  returnOnAssets: number
  returnOnEquity: number
  grossProfitMargin: number
  netProfitMargin: number
}
export interface FinancialReport {
  reportType: string
  period: string
  totalRevenue: number
  totalExpenses: number
  grossProfit: number
  netIncome: number
  ebitda: number
}
export declare function calculateAccountBalance(transactions: Array<Transaction>): number
export declare function calculateBudgetVariance(budgetedAmount: number, actualAmount: number): BudgetAnalysis
export declare function calculateCashFlowProjection(openingBalance: number, inflows: Array<number>, outflows: Array<number>): CashFlowProjection
export declare function calculateFinancialRatios(currentAssets: number, currentLiabilities: number, quickAssets: number, totalDebt: number, totalEquity: number, totalAssets: number, netIncome: number, revenue: number, costOfGoodsSold: number): FinancialRatios
export declare function calculateDepreciationStraightLine(assetCost: number, salvageValue: number, usefulLifeYears: number): number
export declare function calculateDepreciationDecliningBalance(bookValue: number, depreciationRate: number): number
export declare function calculateLoanPayment(principal: number, annualInterestRate: number, loanTermYears: number): number
export declare function calculateFinancialBreakEvenPoint(fixedCosts: number, variableCostPerUnit: number, sellingPricePerUnit: number): number
export declare function calculateCostOfCapital(costOfDebt: number, costOfEquity: number, marketValueDebt: number, marketValueEquity: number, taxRate: number): number
export declare function calculateEconomicValueAdded(netOperatingProfitAfterTax: number, investedCapital: number, costOfCapital: number): number
export declare function generateFinancialReport(revenue: number, costOfGoodsSold: number, operatingExpenses: number, interestExpense: number, taxExpense: number, depreciationExpense: number): FinancialReport
export declare function calculateWorkingCapitalRatio(currentAssets: number, currentLiabilities: number): number
export declare function calculateFinancialInventoryTurnover(costOfGoodsSold: number, averageInventory: number): number
export declare function calculateFinancialDaysSalesOutstanding(accountsReceivable: number, annualSales: number): number
export interface Employee {
  employeeId: string
  name: string
  position: string
  department: string
  hireDate: string
  salary: number
  currency: string
  employmentType: string
  performanceRating: number
}
export interface PayrollCalculation {
  employeeId: string
  baseSalary: number
  overtimeHours: number
  overtimeRate: number
  overtimePay: number
  grossPay: number
  taxDeductions: number
  benefitDeductions: number
  netPay: number
}
export interface PerformanceMetrics {
  employeeId: string
  goalsCompleted: number
  totalGoals: number
  qualityScore: number
  productivityScore: number
  teamworkScore: number
  overallPerformanceScore: number
  performanceLevel: string
}
export interface BenefitCalculation {
  employeeId: string
  healthInsurance: number
  dentalInsurance: number
  retirementContribution: number
  lifeInsurance: number
  totalBenefitsValue: number
}
export interface WorkforceAnalytics {
  totalEmployees: number
  averageSalary: number
  turnoverRate: number
  averagePerformanceScore: number
  departmentHeadcount: Array<DepartmentHeadcount>
  totalPayrollCost: number
}
export interface DepartmentHeadcount {
  department: string
  employeeCount: number
  averageSalary: number
}
export interface TimeTracking {
  employeeId: string
  regularHours: number
  overtimeHours: number
  vacationHours: number
  sickHours: number
  totalHours: number
}
export declare function calculatePayroll(baseSalary: number, overtimeHours: number, overtimeMultiplier: number, taxRate: number, benefitDeductions: number, payPeriodsPerYear: number): PayrollCalculation
export declare function calculatePerformanceScore(goalsCompleted: number, totalGoals: number, qualityScore: number, productivityScore: number, teamworkScore: number): PerformanceMetrics
export declare function calculateBenefitsValue(salary: number, healthInsurancePercentage: number, dentalInsurancePercentage: number, retirementMatchPercentage: number, lifeInsuranceFlatRate: number): BenefitCalculation
export declare function calculateTurnoverRate(employeesLeft: number, averageHeadcount: number, periodMonths: number): number
export declare function calculateSalaryIncreaseRecommendation(currentSalary: number, performanceScore: number, marketAdjustment: number, budgetConstraint: number): number
export declare function calculateCostPerHire(totalRecruitingCost: number, numberOfHires: number): number
export declare function calculateEmployeeProductivity(revenueGenerated: number, hoursWorked: number): number
export declare function calculateTrainingRoi(trainingCost: number, productivityImprovement: number, employeeSalary: number, trainingPeriodMonths: number): number
export declare function calculateCompensationRatio(employeeSalary: number, marketMedianSalary: number): number
export declare function generateWorkforceAnalytics(employees: Array<Employee>, turnoverCount: number, periodMonths: number): WorkforceAnalytics
export declare function calculateOvertimeThreshold(regularHoursPerWeek: number, overtimeMultiplier: number, targetCostIncrease: number): number
export interface ProductionOrder {
  orderId: string
  productId: string
  quantityPlanned: number
  quantityProduced: number
  startDate: string
  endDate: string
  status: string
  priority: number
}
export interface WorkCenter {
  workCenterId: string
  name: string
  capacityPerHour: number
  efficiencyRate: number
  availabilityHours: number
  currentUtilization: number
}
export interface ProductionSchedule {
  workCenterId: string
  productionOrders: Array<string>
  totalScheduledHours: number
  capacityUtilization: number
  completionDate: string
}
export interface ManufacturingQualityMetrics {
  batchId: string
  totalUnits: number
  defectiveUnits: number
  defectRate: number
  firstPassYield: number
  reworkRate: number
  scrapRate: number
}
export interface ProductionEfficiency {
  workCenterId: string
  plannedProductionTime: number
  actualProductionTime: number
  efficiencyPercentage: number
  downtimeHours: number
  setupTimeHours: number
  oeeScore: number
}
export interface BillOfMaterials {
  productId: string
  components: Array<MaterialComponent>
  totalMaterialCost: number
  laborCost: number
  overheadCost: number
  totalCost: number
}
export interface MaterialComponent {
  componentId: string
  quantityRequired: number
  unitCost: number
  totalCost: number
  leadTimeDays: number
}
export declare function calculateProductionCapacity(workCenters: Array<WorkCenter>, plannedHours: number): number
export declare function calculateProductionTimeRequired(quantity: number, productionRatePerHour: number, setupTimeHours: number): number
export declare function calculateOeeScore(availabilityPercentage: number, performancePercentage: number, qualityPercentage: number): number
export declare function optimizeProductionSequence(orders: Array<string>, priorities: Array<number>, processingTimes: Array<number>): Array<string>
export declare function calculateMaterialRequirements(productionQuantity: number, components: Array<MaterialComponent>): BillOfMaterials
export declare function calculateCycleTime(setupTime: number, processingTimePerUnit: number, batchSize: number): number
export declare function calculateProductionEfficiency(plannedOutput: number, actualOutput: number, plannedTime: number, actualTime: number): ProductionEfficiency
export declare function calculateBatchSizeOptimization(annualDemand: number, setupCost: number, holdingCostPerUnit: number): number
export declare function calculateChangeoverTime(fromProductId: string, toProductId: string, baseChangeoverTime: number, complexityFactor: number): number
export declare function calculateCapacityUtilization(scheduledHours: number, availableHours: number): number
export declare function calculateProductionCostPerUnit(totalMaterialCost: number, totalLaborCost: number, totalOverheadCost: number, quantityProduced: number): number
export declare function calculateLeadTimeVariance(plannedLeadTimes: Array<number>, actualLeadTimes: Array<number>): number
export declare function calculateWorkCenterEfficiency(workCenters: Array<WorkCenter>): number
