/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function hello_digital_forensics(): string
export function calculate_sample_digital_forensics(value: number): number
export function analyze_digital_forensics_metrics(inputData: Array<number>): string
export function get_digital_forensics_info(): string
export function validate_digital_forensics_config(config: string): boolean
export function process_digital_forensics_data(data: string): string