/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function hello_production_planning(): string
export function calculate_sample_production_planning(value: number): number
export function analyze_production_planning_metrics(inputData: Array<number>): string
export function get_production_planning_info(): string
export function validate_production_planning_config(config: string): boolean
export function process_production_planning_data(data: string): string