/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function hello_testing_validation(): string
export function calculate_sample_testing_validation(value: number): number
export function analyze_testing_validation_metrics(inputData: Array<number>): string
export function get_testing_validation_info(): string
export function validate_testing_validation_config(config: string): boolean
export function process_testing_validation_data(data: string): string