/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Basic function for Human Resources */
export declare function helloHr(): string
/** Sample calculation for Human Resources */
export declare function calculateSample(value: number): number
/** Get module info */
export declare function getModuleInfo(): string
