/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function hello_lean_manufacturing(): string
export function calculate_sample_lean_manufacturing(value: number): number
export function analyze_lean_manufacturing_metrics(inputData: Array<number>): string
export function get_lean_manufacturing_info(): string
export function validate_lean_manufacturing_config(config: string): boolean
export function process_lean_manufacturing_data(data: string): string