/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Account types in the financial system */
export const enum AccountType {
  Asset = 'Asset',
  Liability = 'Liability',
  Equity = 'Equity',
  Revenue = 'Revenue',
  Expense = 'Expense'
}
/** Financial account data structure */
export interface Account {
  id: string
  accountCode: string
  accountName: string
  accountType: string
  parentAccountId?: string
  currentBalance: number
  debitBalance: number
  creditBalance: number
  isActive: boolean
  createdAt: string
  updatedAt: string
}
/** Journal entry for double-entry bookkeeping */
export interface JournalEntry {
  id: string
  entryNumber: string
  description: string
  transactionDate: string
  totalDebit: number
  totalCredit: number
  isBalanced: boolean
  createdBy: string
  status: string
}
/** Individual line item in a journal entry */
export interface JournalLineItem {
  id: string
  journalEntryId: string
  accountId: string
  description: string
  debitAmount: number
  creditAmount: number
  referenceNumber?: string
}
/** Financial statement data */
export interface FinancialStatement {
  statementType: string
  periodStart: string
  periodEnd: string
  totalAssets: number
  totalLiabilities: number
  totalEquity: number
  totalRevenue: number
  totalExpenses: number
  netIncome: number
}
/** Account receivable record */
export interface AccountReceivable {
  id: string
  customerId: string
  invoiceNumber: string
  invoiceAmount: number
  amountPaid: number
  amountDue: number
  dueDate: string
  daysOverdue: number
  agingBucket: string
}
/** Account payable record */
export interface AccountPayable {
  id: string
  vendorId: string
  invoiceNumber: string
  invoiceAmount: number
  amountPaid: number
  amountDue: number
  dueDate: string
  daysUntilDue: number
  discountAvailable: number
  discountDate?: string
}
/** Cash flow statement data */
export interface CashFlowStatement {
  operatingCashFlow: number
  investingCashFlow: number
  financingCashFlow: number
  netCashFlow: number
  beginningCash: number
  endingCash: number
  periodStart: string
  periodEnd: string
}
/** Create a new financial account */
export declare function createAccount(accountCode: string, accountName: string, accountType: string, parentAccountId?: string | undefined | null): Account
/** Calculate account balance */
export declare function calculateAccountBalance(debitAmount: number, creditAmount: number, accountType: string): number
/** Create a journal entry with automatic balancing validation */
export declare function createJournalEntry(description: string, transactionDate: string, lineItems: Array<JournalLineItem>): JournalEntry
/** Calculate financial ratios */
export declare function calculateCurrentRatio(currentAssets: number, currentLiabilities: number): number
/** Calculate debt-to-equity ratio */
export declare function calculateDebtToEquityRatio(totalDebt: number, totalEquity: number): number
/** Calculate return on assets (ROA) */
export declare function calculateReturnOnAssets(netIncome: number, totalAssets: number): number
/** Calculate return on equity (ROE) */
export declare function calculateReturnOnEquity(netIncome: number, totalEquity: number): number
/** Calculate gross profit margin */
export declare function calculateGrossProfitMargin(grossProfit: number, revenue: number): number
/** Calculate net profit margin */
export declare function calculateNetProfitMargin(netIncome: number, revenue: number): number
/** Calculate days sales outstanding (DSO) */
export declare function calculateDaysSalesOutstanding(accountsReceivable: number, dailySales: number): number
/** Calculate accounts receivable aging */
export declare function calculateArAging(arRecords: Array<AccountReceivable>): string
/** Calculate compound annual growth rate (CAGR) */
export declare function calculateCagr(beginningValue: number, endingValue: number, years: number): number
/** Calculate present value */
export declare function calculatePresentValue(futureValue: number, discountRate: number, periods: number): number
/** Calculate future value */
export declare function calculateFutureValue(presentValue: number, interestRate: number, periods: number): number
/** Generate financial statement */
export declare function generateFinancialStatement(periodStart: string, periodEnd: string, accounts: Array<Account>): FinancialStatement
/** Calculate working capital */
export declare function calculateWorkingCapital(currentAssets: number, currentLiabilities: number): number
/** Calculate quick ratio (acid test) */
export declare function calculateQuickRatio(quickAssets: number, currentLiabilities: number): number
/** Calculate inventory turnover ratio */
export declare function calculateInventoryTurnover(costOfGoodsSold: number, averageInventory: number): number
/** Calculate break-even point */
export declare function calculateBreakEvenPoint(fixedCosts: number, pricePerUnit: number, variableCostPerUnit: number): number
