/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function hello_credit_risk(): string
export function calculate_sample_credit_risk(value: number): number
export function analyze_credit_risk_metrics(inputData: Array<number>): string
export function get_credit_risk_info(): string
export function validate_credit_risk_config(config: string): boolean
export function process_credit_risk_data(data: string): string