/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function hello_digital_twin(): string
export function calculate_sample_digital_twin(value: number): number
export function analyze_digital_twin_metrics(inputData: Array<number>): string
export function get_digital_twin_info(): string
export function validate_digital_twin_config(config: string): boolean
export function process_digital_twin_data(data: string): string