/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Basic function for Customer Relationship Management */
export declare function helloCrm(): string
/** Sample calculation for Customer Relationship Management */
export declare function calculateSample(value: number): number
/** Get module info */
export declare function getModuleInfo(): string
