/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function hello_international_trade(): string
export function calculate_sample_international_trade(value: number): number
export function analyze_international_trade_metrics(inputData: Array<number>): string
export function get_international_trade_info(): string
export function validate_international_trade_config(config: string): boolean
export function process_international_trade_data(data: string): string