/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface EducationRecord {
  id: string
  name: string
  description?: string
  status: string
  createdAt: string
  updatedAt: string
}
export class EducationRecord {
  constructor(name: string, description?: string, status: string)
  updateStatus(newStatus: string): void
  getAgeInDays(): number
}
export function getModuleInfo(): string
export function validateeducation_data(data: string): boolean
