/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function hello_regulatory_reporting(): string
export function calculate_sample_regulatory_reporting(value: number): number
export function analyze_regulatory_reporting_metrics(inputData: Array<number>): string
export function get_regulatory_reporting_info(): string
export function validate_regulatory_reporting_config(config: string): boolean
export function process_regulatory_reporting_data(data: string): string