/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function hello_neural_networks(): string
export function calculate_sample_neural_networks(value: number): number
export function analyze_neural_networks_metrics(inputData: Array<number>): string
export function get_neural_networks_info(): string
export function validate_neural_networks_config(config: string): boolean
export function process_neural_networks_data(data: string): string