/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function hello_factory_automation(): string
export function calculate_sample_factory_automation(value: number): number
export function analyze_factory_automation_metrics(inputData: Array<number>): string
export function get_factory_automation_info(): string
export function validate_factory_automation_config(config: string): boolean
export function process_factory_automation_data(data: string): string