/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function hello_predictive_analytics(): string
export function calculate_sample_predictive_analytics(value: number): number
export function analyze_predictive_analytics_metrics(inputData: Array<number>): string
export function get_predictive_analytics_info(): string
export function validate_predictive_analytics_config(config: string): boolean
export function process_predictive_analytics_data(data: string): string