/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function hellosales(): string
export function calculateSample(value: number): number
export function getModuleInfo(): string
