/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function hello_algorithmic_trading(): string
export function calculate_sample_algorithmic_trading(value: number): number
export function analyze_algorithmic_trading_metrics(inputData: Array<number>): string
export function get_algorithmic_trading_info(): string
export function validate_algorithmic_trading_config(config: string): boolean
export function process_algorithmic_trading_data(data: string): string