/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function hello_quantum_computing(): string
export function calculate_sample_quantum_computing(value: number): number
export function analyze_quantum_computing_metrics(inputData: Array<number>): string
export function get_quantum_computing_info(): string
export function validate_quantum_computing_config(config: string): boolean
export function process_quantum_computing_data(data: string): string