/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function hello_regulatory_compliance(): string
export function calculate_sample_regulatory_compliance(value: number): number
export function analyze_regulatory_compliance_metrics(inputData: Array<number>): string
export function get_regulatory_compliance_info(): string
export function validate_regulatory_compliance_config(config: string): boolean
export function process_regulatory_compliance_data(data: string): string