/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function hello_advanced_manufacturing(): string
export function calculate_sample_advanced_manufacturing(value: number): number
export function analyze_advanced_manufacturing_metrics(inputData: Array<number>): string
export function get_advanced_manufacturing_info(): string
export function validate_advanced_manufacturing_config(config: string): boolean
export function process_advanced_manufacturing_data(data: string): string