/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface TreasuryRecord {
  id: string
  name: string
  description?: string
  status: string
  createdAt: string
  updatedAt: string
}
export declare function createTreasuryRecord(name: string, description: string | undefined | null, status: string): TreasuryRecord
export declare function updateTreasuryRecordStatus(record: TreasuryRecord, newStatus: string): TreasuryRecord
export declare function calculateCashFlow(inflows: Array<number>, outflows: Array<number>): number
export declare function calculateInvestmentYield(initialValue: number, currentValue: number, timePeriod: number): number
export declare function optimizeCashPosition(targetBalance: number, currentBalance: number): string
export declare function getModuleInfo(): string
export declare function validateTreasuryData(data: string): boolean
