/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function hello_computer_vision(): string
export function calculate_sample_computer_vision(value: number): number
export function analyze_computer_vision_metrics(inputData: Array<number>): string
export function get_computer_vision_info(): string
export function validate_computer_vision_config(config: string): boolean
export function process_computer_vision_data(data: string): string