/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function hello_edge_computing(): string
export function calculate_sample_edge_computing(value: number): number
export function analyze_edge_computing_metrics(inputData: Array<number>): string
export function get_edge_computing_info(): string
export function validate_edge_computing_config(config: string): boolean
export function process_edge_computing_data(data: string): string