/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function hello_augmented_reality(): string
export function calculate_sample_augmented_reality(value: number): number
export function analyze_augmented_reality_metrics(inputData: Array<number>): string
export function get_augmented_reality_info(): string
export function validate_augmented_reality_config(config: string): boolean
export function process_augmented_reality_data(data: string): string