/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function hello_autonomous_systems(): string
export function calculate_sample_autonomous_systems(value: number): number
export function analyze_autonomous_systems_metrics(inputData: Array<number>): string
export function get_autonomous_systems_info(): string
export function validate_autonomous_systems_config(config: string): boolean
export function process_autonomous_systems_data(data: string): string